# Generated by Django 5.2.6 on 2026-04-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_profilemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='image',
            field=models.ImageField(default='user_profile_images/default_profile.png', upload_to='user_profile_images'),
        ),
    ]
