# Generated by Django 5.2.6 on 2026-04-24 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_profilemodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='user',
        ),
    ]
