# Generated by Django 5.2.6 on 2026-04-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_profilemodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user_profile_images'),
        ),
    ]
