# Generated by Django 5.2.6 on 2026-04-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_profilemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='image',
            field=models.ImageField(blank=True, default='user_profile_images/default_profile.png', null=True, upload_to='user_profile_images'),
        ),
    ]
