# Generated by Django 5.2.6 on 2026-04-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_categorymodel_image_alter_productmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='image',
            field=models.ImageField(blank=True, default='category_images/default_product.png', null=True, upload_to='category_images'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='image',
            field=models.ImageField(blank=True, default='product_images/default_product.png', null=True, upload_to='product_images'),
        ),
    ]
