# Generated by Django 5.2.6 on 2026-04-28 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_messagemodel_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagemodel',
            old_name='message',
            new_name='user_message',
        ),
    ]
