# Generated by Django 5.2.6 on 2026-04-29 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_rename_message_messagemodel_user_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagemodel',
            old_name='user',
            new_name='author',
        ),
    ]
