# Generated by Django 5.2.6 on 2026-05-02 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_wishlistmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlistmodel',
            options={'verbose_name': 'WishList', 'verbose_name_plural': 'WishLists'},
        ),
    ]
