# Generated by Django 5.2.6 on 2026-05-05 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_cartmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='tag',
        ),
        migrations.AlterModelOptions(
            name='cartmodel',
            options={'verbose_name': 'Cart Item', 'verbose_name_plural': 'Cart Items'},
        ),
        migrations.DeleteModel(
            name='TagModel',
        ),
    ]
