# Generated by Django 5.2.6 on 2026-05-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_remove_productmodel_tag_alter_cartmodel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartmodel',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='cartmodel',
            name='quantity',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='total_cost',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
