# Generated by Django 5.2.6 on 2026-05-05 10:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_remove_cartmodel_cost_remove_cartmodel_quantity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartModel',
            new_name='CartListModel',
        ),
    ]
