# Generated by Django 5.2.6 on 2026-05-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_rename_cartmodel_cartlistmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='total_cost',
        ),
        migrations.AddField(
            model_name='cartlistmodel',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
