# Generated by Django 5.2.6 on 2026-05-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_orderlistmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlistmodel',
            name='cart_item',
        ),
        migrations.AddField(
            model_name='orderlistmodel',
            name='cart_item',
            field=models.ManyToManyField(blank=True, to='myapp.cartlistmodel'),
        ),
    ]
