# Generated by Django 5.2.6 on 2026-05-06 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_remove_orderlistmodel_cart_item_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlistmodel',
            old_name='cart_item',
            new_name='cart_items',
        ),
    ]
