# Generated by Django 5.2.6 on 2026-05-07 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_rename_cart_item_orderlistmodel_cart_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlistmodel',
            name='cart_items',
        ),
        migrations.AddField(
            model_name='orderlistmodel',
            name='cart_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.cartlistmodel'),
        ),
    ]
