# Generated by Django 5.2.6 on 2026-05-07 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_remove_orderlistmodel_cart_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlistmodel',
            name='product',
        ),
    ]
