# Generated by Django 5.2.6 on 2026-05-07 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_remove_orderlistmodel_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlistmodel',
            name='cart_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.cartlistmodel'),
        ),
    ]
