# Generated by Django 5.2.6 on 2026-05-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_alter_orderlistmodel_cart_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartlistmodel',
            name='is_ordered',
            field=models.BooleanField(default=False),
        ),
    ]
